/**
 * Gateway 错误码常量
 *
 * 替代 contracts/memory/error-codes.json
 * 所有 Gateway 错误码集中在此定义，SDK 和 Gateway 共享引用。
 */

/** Gateway 层错误码（范围: 7000-7999） */
export const MEMORY_GATEWAY = {
  UNAUTHENTICATED: "MEMORY_UNAUTHENTICATED",
  FORBIDDEN: "MEMORY_FORBIDDEN",
  INVALID_REQUEST: "MEMORY_INVALID_REQUEST",
  USER_NOT_FOUND: "MEMORY_USER_NOT_FOUND",
  CONVERSATION_NOT_FOUND: "MEMORY_CONVERSATION_NOT_FOUND",
  MEMORY_NOT_FOUND: "MEMORY_NOT_FOUND",
  CONFLICT: "MEMORY_CONFLICT",
  SEMANTIC_DUPLICATE: "MEMORY_SEMANTIC_DUPLICATE",
  INDEX_PENDING: "MEMORY_INDEX_PENDING",
  EMBEDDING_UNAVAILABLE: "MEMORY_EMBEDDING_UNAVAILABLE",
  VECTORIZE_UNAVAILABLE: "MEMORY_VECTORIZE_UNAVAILABLE",
  QUOTA_EXCEEDED: "MEMORY_QUOTA_EXCEEDED",
  IDEMPOTENCY_REQUIRED: "MEMORY_IDEMPOTENCY_REQUIRED",
  IDEMPOTENCY_CONFLICT: "MEMORY_IDEMPOTENCY_CONFLICT",
  INTERNAL_ERROR: "MEMORY_INTERNAL_ERROR",
} as const;

/** D1 数据库错误码（范围: 7100-7199） */
export const MEMORY_D1 = {
  CONSTRAINT_VIOLATION: "MEMORY_D1_CONSTRAINT",
  QUOTA_EXCEEDED: "MEMORY_D1_QUOTA",
} as const;

/** Vectorize 错误码（范围: 7200-7299） */
export const MEMORY_VECTORIZE = {
  DIMENSION_MISMATCH: "MEMORY_VEC_DIMENSION",
  INDEX_NOT_FOUND: "MEMORY_VEC_NOT_FOUND",
} as const;
